import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { ApiProvider } from "@/lib/ApiContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100 `}>
        <ApiProvider>
          {/* navbar */}
          <NavBar />
          <div className="px-10 py-5">{children}</div>
        </ApiProvider>
      </body>
    </html>
  );
}
